name: C/C++ CI

on:
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get install make
    - name: make all
      run: make -C 3_Implementation

