name: cpp check

on:
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt-get -y install cppcheck
    - name: Cppcheck code
      run: cppcheck 3_Implementation/
