name: Build Window

on:
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

jobs:
  build:

    runs-on: window-10

    steps:
    - uses: actions/checkout@v2

    - name: make all
      run: make all -C 3_Implementation/

